### ISSUE TITLE
Mapping.txt questions

### ISSUE THREAD

**Issue by mrlinuxfish** [apocatarsis/Naga_KeypadMapper#10]
First off, I seem to have got this working on a naga 2012. Second, what conventions are used for th mapping.txt file? I can't seem to map a button to the escape key.

**Comment by apocatarsis** [comment]
The syntax in mapping.txt for the keys is the one of xdotool minus de "XK_". You can see all keys here: http://cgit.freedesktop.org/xorg/proto/x11proto/plain/keysymdef.h

According to this, the ESC button would be: "Escape"

You can see the syntax for the mapping.txt in the README.

Thanks for your feedbak!

**Comment by Destroyer** [comment]
Hi, any changes you have to made to the code? If any let us know so that we can add it to the support list :)
The list of possible keys is mentioned but if you wanna test it, you can run `xdotool key --window getactivewindow KEYorSHORTCUT` from your terminal and if it doesn't print something like `(symbol) No such key name 'X'. Ignoring it.` then it works.

**Comment by mrlinuxfish** [comment]
I am running on arch linux, so I installed all the dependencies and manually ran most of the commands from install.sh as it didn't run correctly the first time.

**Comment by apocatarsis** [comment]
So the core executable was compatible without any changes?

**Comment by mrlinuxfish** [comment]
The executable would not run, but the commands in the executable worked. The only odd thing is the mapping file it is using is in /root/.naga/ instead of ~/.naga because the executable has to be run using sudo.

**Comment by Destroyer** [comment]
I don't think it's that odd, the naga executable uses getenv() to find out where's the home. So if this variable gets changed with sudo, it will load its changed version. 
What's odd to me is that I've read the udev rules syntax on archlinux wiki and it doesnt work for you. Did you try to update them? ( http://unix.stackexchange.com/a/39371 ). If you add yourself to that group you should be able to read those commands without sudo.

Also my question is: with what parametr does it call itself? With `sudo naga molten` or different? So that I can add it to readme. :)
