### ISSUE TITLE
Sudo, $SUDO_USER and $HOME

### ISSUE THREAD

**Issue by apocatarsis** [apocatarsis/Naga_KeypadMapper#14]
Ideally mapping.txt goes into the home folder of some user. But if you need to run install.sh or the naga executable as root the $HOME variable is set to /root (at least in my system), so it is not ideal to read/write mapping.txt using $HOME.
The solution could be to use SUDO_USER instead of HOME. This works in my system, but I do not know if its safe.

**Comment by Destroyer** [comment]
you can try
```
# useradd  -m -d /mnt/bar foo
# adduser foo sudo
# su foo
$ cd ~
$ echo "echo $SUDO_USER" > test.sh
$ sudo sh test.sh
```

**Comment by apocatarsis** [comment]
Sorry, I did not explain myself well. In the install script I just changed the HOME variable using getent passwd $SUDO_USER. So that is ok. But yeah, as you have root you can just su USER. Good idea, I will keep it in mind.
I meant in naga.cpp, you need to read the configuration from $HOME of the user, but with getenv you get home of root (is this true btw?). I changed so the mapping.txt is read from /home/$SUDO_USER/.naga . But this is not necessarily general.

**Comment by apocatarsis** [comment]
BTW, I am not able to autostart it. Calling naga at the end of nagastart doesnt seem to be enough. And calling sudo naga asks for password, so you cannot auto start it. Any ideas?.
For the moment I am just starting it manually with nohup sudo nagastart.sh > /dev/null

**Comment by Destroyer** [comment]
1. It depends on who owns the process(in most cases). If it's run via root it will check default variable $HOME of root (if not set otherwise). And since we start this tool (at least in ubuntu) with autostart in users profile and the process that starts it owns the user, it does uses his home. 
Also I don't  think that you need any tweaking of the executable, if you want to specify HOME for naga executable you can edit nagastart.sh to include `export HOME=path` and put whatever you need there (if you're the only user, otherwise you need to call it from somewhere else, child processes will share these env variables).

2. I've made it so that sudo shouldn't be neccessary. Either you can chmod the naga events in /dev/input with `chmod o+r` or you use this https://github.com/apocatarsis/Naga_KeypadMapper/blob/master/install.sh#L46-L48 
either way the executable should work without root privilidges, that was my intention

**Comment by apocatarsis** [comment]
1. Yeah the export HOME is much secure. I'll change it.

2. Oh really? I'll check later, not needing root would be dope!

**Comment by apocatarsis** [comment]
Ok so now I am a bit lost. Please give me a hand whenever you can. I think I may screwed up a little. Using the current master:
     1. Where does the install.sh copy mapping.txt?, /root/.naga or /home/user/.naga??
     2. Where does naga.cpp looks for mapping.txt?, in /root/.naga or /home/user/.naga??
I think the problem with the user in the other issue could be related to this.

Thank you very much Destroyer. I appologize for the inconvinience..

**Comment by Destroyer** [comment]
1. I thought you should know since you've pushed this commit, but afaik it should copy mapping.txt to home/user/.naga (but I dunno why using this complicated syntax)
2. as I've said it depends if it's ran by root it looks at /root/ (or $HOME of root) and if it's ran by regular user it looks at /home/user (or $HOME of the user)

but from what I can see I should push merge from testlab as soon as possible so that I can work on just one version and not two

**Comment by Destroyer** [comment]
I am closing this ticket now, if you need more help, just reopen it.
