### ISSUE TITLE
epic chroma in ubuntu 15.10

### ISSUE THREAD

**Issue by drunkscientist** [apocatarsis/Naga_KeypadMapper#17]
first attempt at installing naga epic chroma in ubuntu failed, at first i thought it might be because i was using it wirelessly and i know windows recognizes the dock seperatly from the mouse so i uninstalled everything, plugged it in directly but get the same error at boot:

`error fount when loading /home/username/.profile:

terminate called after throwing an instance of 'std:;logic_error'
what(): basic_string::_M_construct null not valid
/sur/local/bin/nagastart.sh: line 19: 951 Aborted             (core
dumped) naga chroma

As a result the session will not be configured correctly.
You should fix the problem as soon as feasible.`

not entirely sure what to try next; or if i should have left that last line in nagastart.sh as just naga instead of adding chroma, or something else. also major props on making this whole thing, really hoping i can get it to work because it looks sooo much simpler than any of the other daemons that have been made and since depreciated

**Comment by khornem** [comment]
Could you send `ls -l /dev/input/by-id/` ?

If you try to start the daemon manually `/usr/local/bin/naga chroma` what output do you get?

**Comment by drunkscientist** [comment]
when its unplugged i get:

`lrwxrwxrwx 1 root root  9 Feb  6 13:50 usb-Razer_Razer_Naga_Epic_Chroma_Dock-event-mouse -> ../event3

lrwxrwxrwx 1 root root  9 Feb  6 13:50 usb-Razer_Razer_Naga_Epic_Chroma_Dock-if01-event-kbd -> ../event4

lrwxrwxrwx 1 root root  9 Feb  6 13:50 usb-Razer_Razer_Naga_Epic_Chroma_Dock-if02-event-kbd -> ../event5

lrwxrwxrwx 1 root root  9 Feb  6 13:50 usb-Razer_Razer_Naga_Epic_Chroma_Dock-mouse -> ../mouse0`

and plugging it in changes it to:

`lrwxrwxrwx 1 root root  9 Feb  6 14:08 usb-Razer_Razer_Naga_Epic_Chroma-event-mouse -> ../event3

lrwxrwxrwx 1 root root  9 Feb  6 14:08 usb-Razer_Razer_Naga_Epic_Chroma-if01-event-kbd -> ../event4

lrwxrwxrwx 1 root root  9 Feb  6 14:08 usb-Razer_Razer_Naga_Epic_Chroma-if02-event-kbd -> ../event5

lrwxrwxrwx 1 root root  9 Feb  6 14:08 usb-Razer_Razer_Naga_Epic_Chroma-mouse -> ../mouse0
`

running daemon in terminal returns:
`terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted (core dumped)
`

**Comment by khornem** [comment]
Do you get the same error when it is plugged to your pc using the usb cable and when it is used wirelessly?

**Comment by drunkscientist** [comment]
yes, at least so far i have

**Comment by Destroyer** [comment]
Can you please check testlab branch and see if that code works or prints something? just compile it with g++ naga.cpp -o naga and move the output file to /usr/local/bin and replace it with that naga - and try to run it with naga chroma if it prints anything else other than this

**Comment by drunkscientist** [comment]
will try when i get home. i uninstalled everything again so the thumb buttons would work, can i just replace the naga.cpp file and then bash install.sh again or use the whole testlab branch? or compile>move>run as described?

**Comment by apocatarsis** [comment]
The .profile thing is on me, lesson learned, sorry guys, rolling back to previous naga.desktop method... 
**drunkscientist, if you unninstall, clone the new master version of the repository and install again, it should work with the mouse plugged.**. It is safe to use install.sh again. Sorry for the hassle.

As for the Dock thing, The code doesnt recognize "usb-Razer_Razer_Naga_Epic_Chroma_Dock-if01-event-kbd", it just looks for "usb-Razer_Razer_Naga_Epic_Chroma-if01-event-kbd". However you can change this very easily in the code, just adding the missing "_Dock-" in naga.cpp (in the devices const *char). Whenever we can we will add dock support, as it doesnt sound very difficult.

As for the error in the daemon, compile with g++ -O2 -std=c++11 -g naga.cpp -o naga and run with $sudo naga chroma
Should work out of the box with the plugged chroma. If it doesnt, luckily it will tell you the line where it happend so we can gain some insight on this bug.

The error could be due to the program not finding mapping.txt, so be sure mapping.txt is in /home/username/.naga (otherwise try /root/.naga/, as running naga using sudo sets $HOME to /root).

**Comment by Destroyer** [comment]
Allright I've merged changes from testlab and updated installation script. In case it fails it won't run the daemon. Also merged version should report errors that occur better(hopefully). Give it a shot and let us know.

**Comment by drunkscientist** [comment]
so i forgot to plug it in before installing but after plugging it in and starting it it does now work! thanks guys this is awesome. definately gonna recompile for the dock though, i almost never use this thing plugged in. amazing work, much thanks!

**Comment by Destroyer** [comment]
No problem, in case of other issues, feel free to reopen :)
