### ISSUE TITLE
Running shortcut inside gnome-terminal

### ISSUE THREAD

**Issue by dmitry-saritasa** [apocatarsis/Naga_KeypadMapper#34]
**Great solution!** Saves a lot of time!

If I make a key press - then in my gnome terminal I see the number I pressed (although the command binded to that key has executed successfully ) how to get rid of that trail numbers in terminal?

**Comment by apocatarsis** [comment]
Sorry, I had not see this issue until now. Hope you got it figured out. If nagastart.sh fails to disable them. The trick is this line:

In order to get rid of the original bindings it disables the keypad using xinput as follows:

$ xinput set-int-prop [id] "Device Enabled" 8 0

where [id] is the id number of the keypad returned by $ xinput.

I am closing this because it is very old, but please feel free to reopen if you are still interested or have further issues.
