### ISSUE TITLE
Can't get model rz01-0104 configured correctly (Naga 2014)

### ISSUE THREAD

**Issue by octoxan** [apocatarsis/Naga_KeypadMapper#40]
I've gone through the guide a few times, and checked over other open issues and can't seem to figure this out.

I've customized the ~/.naga/mapping_01.txt but the key bindings still seem to be doing other things.

My mapping_01.txt looks like this..

```
1 - key=ctrl+shift+q
2 - key=ctrl+shift+q
3 - key=ctrl+shift+q
4 - key=ctrl+shift+q
5 - key=ctrl+shift+q
6 - key=ctrl+shift+q
7 - key=ctrl+shift+q
8 - key=ctrl+shift+q
9 - key=ctrl+shift+q
10 - key=ctrl+shift+q
11 - key=ctrl+shift+q
12 - key=ctrl+shift+q
13 - key=ctrl+shift+q
14 - key=ctrl+shift+q
```

just as a test. But when I type it still types out the number, and does weird random other stuff. Pressing 2 will type out "2" but then it will also close whatever active window I have selected. My ctrl+shift+q on the keyboard opens up terminal...

Would anyone mind helping me troubleshoot this?

**Comment by apocatarsis** [comment]
What system are you on?
In some systems you might have to put mapping_01.txt under $ROOT_HOME/.naga/ . Check that there is no .naga folder there. Or try putting your mapping there.

In the example mapping_02.txt the button "2" does ctrl+w, which usually closes a window. Maybe you are getting that file as active somehow, try with the other buttons. i.e "1" should do ctrl+t, which opens a tab in most browsers.

In my Ubuntu, ctrl+shift+q closes a terminal with all its tabs.

**Comment by apocatarsis** [comment]
In README.md/USAGE you have a walktrough  of what nagastart.sh does. You say that nagastart did not manage to hide the original bindings, so you could try to hide them yourself and see if you get any errors or unexpected behavior.

**Comment by octoxan** [comment]
I'm on Ubuntu Budgie 17.04.

I've now gotten it sort of detecting my key mappings by running "sudo naga", but it's now doing the standard "1" or "2" number keys, as well as my custom key, as well as closing the current window with 1 or 2. For some reason 3-12 seem to be only firing two actions, the standard key press plus my custom key. I reset all my custom keys to just the letter "t" since that seemed the most harmless lol.

Without sudo naga running it does not use my custom key mapping, 3-12 just output 3 through =, while 1 and 2 will output just the number but 2 will occasionally toggle the terminal O.o

xinput does return two id's for me since it's the 2014...

```
xinput get-button-map 14
```
returns with.. 1 2 3 4 5 6 7 11 10

```
xinput get-button-map 15
```
returns with... 1 2 3 4 5 6 7

Now when I run...
```
xinput set-int-prop 14 "Device Enabled" 8 0
```

I can no longer move my mouse at all.

**Comment by octoxan** [comment]
Does it matter than in /dev/input/by-id I have both a

usb-Razer_Razer_Naga_2014-if02-event-kbd

and a

usb-Razer_Razer_Naga_2014-if01-event-kbd

I see only the first one is in the naga.cpp file

**Comment by octoxan** [comment]
Also not sure if after running...
```
xinput set-button-map 14 1 2 3 4 5 6 7 11 10 8 9 13 14 15
```
...are all those then supposed to be returned by get-button-map? Because I still only get 1-7, 11-10

Thank you for your help! Dying to get this working lol

**Comment by apocatarsis** [comment]
naga.cpp looks for the config file in $HOME/.naga/mappings_01.txt
If you run naga with sudo, then $HOME is /root/ or whatever, not the user's home folder. So that is why you get different behavior I suppose. Try taking your mapping_01.txt to the root home aswell.

Yeah, two devs might show up, but only one of them control the side buttons, the other could be the clickers or the wheel or who knows. Every system/mouse seems to be vastly different. Naga 2014 seems to be yet more unlike the others, you can see our tries at handling this in nagastart.sh.

Then again, naga.cpp is so simple in concept that you should be able to use it with little change.

You can check which dev handles the side buttons by:
$sudo cat /dev/input/ONE_OF_THE_TWO_YOU_SAID 
It should print some garbage only when you press a side button.

You have two steps. 
First you have to get rid of the original bindings using some black magic similar to this:
$ xinput set-int-prop [id] "Device Enabled" 8 0
Then again, this step appears to be a little more obtuse in Naga 2014, and I do not know the what is happening in Ubuntu 17, so you will have to play a little with xinput.
The set-button-map is there because apparently naga 2014 labels the buttons in a funny order, so not remapping it could cause things like button 1 doing binding of button 7 or something like that.

If you run:
 $ xinput list-props [id]
You should get a list of properties of the side buttons, including a name, a bunch of information and more importantly a "Device Enabled" flag that when is set to 0, makes xinput ignore the device, so thats the trick nagastart.sh uses basically. If you do this with an incorrect device id, you might end up with the keyboard not writing, the mouse not moving or who knows what disaster.

Then you have to run the naga.cpp  daemon to trigger the custom mapping, that should come down to just running naga. If it doesnt complain and says something like:
    $ Reading from... 
Then you are probably good to go. Be careful however that you have mapping_01.txt in the correct location.

I do not know what is Ubuntu 17 doing in comparison with previous versions that are tested to work, so I am afraid I can only guess and give you some clues...

Let me know how is it going! good luck!

**Comment by octoxan** [comment]
For some reason disabling both 14 and 15 (my naga's ID's) still causes both button presses to happen.

Can't move the mouse, and both 1 + t go through.

Confirmed that the one in naga.cpp is the one that makes all the garbage get sent to the terminal when a side button is pressed. 14 is the one that lists the side buttons when I do list-props, but disabling 14 makes the mouse stop moving but still send side buttons. So not sure I guess.

naga runs without sudo now, but I do have it copied into both locations just in case.

**Comment by apocatarsis** [comment]
Ok, so maybe your naga has the side buttons AND the mouse pointer itself in the same device id, that would be weird, but who knows. You could try disabling another of the naga ids with xinput, see if that rings some bell.

If the bindings are working, silencing the originals is just playing around with xinput.

Instead of setting Device Enabled to 0, maybe you have to change some other property in other to shut down the side buttons and not the rest, you can post the result of xinput list-props for the ids of your naga if you want. Xinput is a mystery to me, so I can only suggest you my approach, press random buttons until the thing you want to happen happens or you get a clue somehow :)

**Comment by octoxan** [comment]
After restarting at least I'm only getting 1t, 2t, 3t, 4t, 5t etc from every button press. No more random terminals opening and windows closing from 1 and 2.

I'll mess around with xinput some more.

I've tried 14 and 15 disabled, 14 disabled with 15 enabled, 14 enabled with 15 disabled... lol

**Comment by apocatarsis** [comment]
You were having problems with the mapping_01.txt location it seems.

Well, maybe you have mode device ids or you have to silence the buttons some other way. Let me know if you find out!

**Comment by octoxan** [comment]
```
xinput list-props 14
```

```
Device 'Razer Razer Naga 2014':
	Device Enabled (166):	1
	Coordinate Transformation Matrix (168):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	libinput Accel Speed (300):	0.000000
	libinput Accel Speed Default (301):	0.000000
	libinput Accel Profiles Available (302):	1, 1
	libinput Accel Profile Enabled (303):	1, 0
	libinput Accel Profile Enabled Default (304):	1, 0
	libinput Natural Scrolling Enabled (305):	0
	libinput Natural Scrolling Enabled Default (306):	0
	libinput Send Events Modes Available (285):	1, 0
	libinput Send Events Mode Enabled (286):	0, 0
	libinput Send Events Mode Enabled Default (287):	0, 0
	libinput Left Handed Enabled (307):	0
	libinput Left Handed Enabled Default (308):	0
	libinput Scroll Methods Available (309):	0, 0, 1
	libinput Scroll Method Enabled (310):	0, 0, 0
	libinput Scroll Method Enabled Default (311):	0, 0, 0
	libinput Button Scrolling Button (312):	2
	libinput Button Scrolling Button Default (313):	2
	libinput Middle Emulation Enabled (314):	0
	libinput Middle Emulation Enabled Default (315):	0
	Device Node (288):	"/dev/input/event8"
	Device Product ID (289):	5426, 64
	libinput Drag Lock Buttons (316):	<no items>
	libinput Horizontal Scroll Enabled (317):	1
```

In case anyone has any idea.

Luckily mapping the top two buttons works perfectly without any extra random input so I'm at least getting a little bit of extra productivity out of two macro buttons... would still be nice to get 12 more =P

**Comment by apocatarsis** [comment]
Device 14 doesnt seem to be related to the side buttons, what about the other? Seems to me 14 is the rest of the mouse

**Comment by octoxan** [comment]
Doing an xinput list-props 15 only gives me...

```
Device 'Razer Razer Naga 2014':
	Device Enabled (166):	1
	Coordinate Transformation Matrix (168):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	libinput Natural Scrolling Enabled (305):	0
	libinput Natural Scrolling Enabled Default (306):	0
	libinput Send Events Modes Available (285):	1, 0
	libinput Send Events Mode Enabled (286):	0, 0
	libinput Send Events Mode Enabled Default (287):	0, 0
	Device Node (288):	"/dev/input/event10"
	Device Product ID (289):	5426, 64
	libinput Drag Lock Buttons (316):	<no items>
	libinput Horizontal Scroll Enabled (317):	1
```

**Comment by octoxan** [comment]
xinput outputs...

```
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ EST Gaming keyboard                     	id=12	[slave  pointer  (2)]
⎜   ↳ Razer Razer Naga 2014                   	id=15	[slave  pointer  (2)]
⎜   ↳ Razer Razer Naga 2014                   	id=14	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Power Button                            	id=8	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=9	[slave  keyboard (3)]
    ↳ EST Gaming keyboard                     	id=13	[slave  keyboard (3)]
    ↳ EST Gaming keyboard                     	id=18	[slave  keyboard (3)]
    ↳ EST Gaming keyboard                     	id=11	[slave  keyboard (3)]
    ↳ Razer Razer Naga 2014                   	id=19	[slave  keyboard (3)]
    ↳ Razer Razer Naga 2014                   	id=16	[slave  keyboard (3)]
```

**Comment by octoxan** [comment]
What's really odd is if I disable both 14 and 15, the mouse cursor stops working but the side buttons still work? >.>

**Comment by apocatarsis** [comment]
I would say that you are looking at the wrong ids, 14 and 15 seem to be under "Virtual core pointer" as in the cursor.

I think you should be looking to the ones under "Virtual core keyboard", that is ids 19 and 16. The side buttons are technically a keyboard, and they behave as such. You see these two devices have a label saying [slave keyboard] while 14 and 15 say [slave pointer]

nagastart.sh tries to find ids 19 and 16 by looking for the lines that contain the keywords Razer, Naga and keyboard using grep. Maybe in your case for some reason you got ids 15 and 14 incorrectly.

So I suggest you try to disable 19 or/and 16 and see what you get. Do the same as before, but ignore completly ids 14 and 15 and work with 19 and 16

**Comment by octoxan** [comment]
Is it normal for all the id's to change on reboot? lol. My slave pointers are now 15 and 17 and slave keyboards are 14 and 16. 

Setting xinput set-int-prop 14 "Device Enabled" 8 0 seems to have solved my problem!

How would I go about getting this to persist with reboot, if the device ID's changed I wouldn't be able to hard code 14 into a script, and running naga doesn't ever seem to disable it on it's own.

Also kind of strange...

xinput get-button-map 14 (or 16) and set-button-map both returns 'device has no buttons'. Actually, every single device listed under virtual core keyboard "has no buttons" when I do get-button-map. >.>

Although at least it's working so I can always just manually disable the correct keyboard one and then run naga on boot, would be nice to get it to persistently disable the device. About to reboot and see if it keeps!

**Comment by octoxan** [comment]
Damn. My .profile does have that line `bash /usr/local/bin/nagastart.sh &` in it, but it doesn't seem to actually run. And my devices that should be disabled are re-enabled, although they did keep their device id's this time. Still 14 and 16. No idea why they changed the first time.. lol

**Comment by apocatarsis** [comment]
So I do not know about the ids changing, maybe it is something ubuntu 17 does, or it is a normal thing, who knows, the good part is that it doesnt matter, because you can get the device using something like grep.

The .profile depends on the distro, and probably ubuntu is just ignoring it, you can just remove it. I do not know how Ubuntu 17 runs script at startup.

For example:
$  ids=$(xinput | grep Naga | grep keyboard | cut -d= -f2 | awk '{print $1}' | paste -sd" ")

This line will return the two correct ids one after the other. If they change when you reboot, so be it.

So now you can do
$ xinput set-int-prop $(echo $ids | awk '{print $1}') "Device Enabled" 8 0
To silence the first device, of use print $2 to silent the second. See the first lines of nagastart.sh

This is what nagastart.sh attempts to do, but has for some reason failed for you, so you can just create your own nagastart.sh whit whatever works for you. I would say that line will work for you.

Just look at nagastart.sh, it does this automatically, so maybe debug line by line and see where it is failing to recognize the ids or whatever.
The thing is that apparently, it is not enough for naga 2014 to just shut off the side buttons, some additional work is needed using set-button-map. But who knows, maybe you dont need to do this.
