### ISSUE TITLE
Linux Mint 17.2 Rafaela Version

### ISSUE THREAD

**Issue by noobxgockel** [apocatarsis/Naga_KeypadMapper#9]
Heya there,

i know you normally shouldnt create issues for saying thanks, but i have the feeling you dont get enough recognition for this ^^

i just wanted to tell you one thing: "THANKS!"
This helped me out quite a bit, because my awesome little Razer Naga Molten Edition mouse was a deal breaker for using linux.

I had to tweak it all a bit, because i have a naga molten edition, but all in all it works c:
Im happy now :grin:

**Comment by Destroyer** [comment]
Let us know what changes you've made in order to make it working so that others will be able to use it without a hassle :)

**Comment by RaulPPelaez** [comment]
Than you very much for your feedback, we are glad to hear that!
As Destroyer pointed, it would help others if you tell as how you tweak the program!. That way we can call this thread an issue :P

**Comment by apocatarsis** [comment]
Than you very much for your feedback, we are glad to hear that!
As Destroyer pointed, it would help others if you tell as how you tweak the program!. That way we can call this thread an issue :P

**Comment by noobxgockel** [comment]
Okay then,
Im using Linux Mint 17.2 Rafaela and the stuff i changed was the following
* Linux Mint doesnt seem to allow the autostart functionality of /root/.config/autostart/ so i put a custom launcher with the "gksu bash /usr/local/bin/nagastart.sh" command in the users autostart (in my case in /home/moe/.config/autostart). I had the problem that now every time the system starts the password needed to be entered, for that i just edited the sudoers file to dont ask for a password in that special case
* inside the nagastart.sh i edited [Line 5](https://github.com/apocatarsis/Naga_KeypadMapper/blob/master/nagastart.sh#L5) to use my version of the naga instead of Naga Epic (My Line 5 looks like this: ```sudo naga /dev/input/by-id/usb-Razer_Razer_Naga-if01-event-kbd```)

The rest did just work then. The only thing im missing is more information about how the mappings.txt file needs to be written. Like i want Naga Button 1 and 4 to do what could be called "Mouse back and forward". The buttons to move back and forward in the browser basicly. But i have no idea what to write in that case. Some documentation or a link for the newbs like me would be nice C:

**Comment by Destroyer** [comment]
Ok thanks for that :) 
1) To address the issue with mint it's kinda hard to do so because every distribution does this differently and I think fixing that issue would make the script even less readable than it already. But I don't know if the author has a different opinion :)

2) Ok, that's what we needed. Thanks. Also if you have some time you can try the other branch (testlab) and test out the two other buttons that are on the side of your naga to see if you can get them working. It's a little bit harder because I've moved the code that uses it directly to the c++ file. So you would have to edit that in order to make it working. But you can make the entire naga work now ;)
e.g. it would look like this

    const char * devices[][2] = {
    		{"/dev/input/by-id/usb-Razer_Razer_Naga_Epic-if01-event-kbd","/dev/input/by-id/usb-Razer_Razer_Naga_Epic-event-mouse"}, // NAGA EPIC
    		{"/dev/input/by-id/usb-Razer_Razer_Naga_2014-if02-event-kbd","/dev/input/by-id/usb-Razer_Razer_Naga_2014-event-mouse"} // NAGA 2014
    		{"/dev/input/by-id/usb-Razer_Razer_Naga-if01-event-kbd","secondDevice"} // NAGA MOLTEN
    };

....

    		else if (strstr(argv[1],"2014"))
    			id = 1;
    		else if (strstr(argv[1],"molten"))
    			id = 2;
    		else
    		{
    			printf("Not valid device. Exiting.\n");
    			exit(1);
    		}



3) If you know some basic of programming you can easily find out how it's done 
At the moment there're 3 possible commands (2 in the stable version)

 `key` which basically runs `xdotool key --window getactivewindow YourShortcut`
so if you wanna make it work and you're not sure about the spelling you can just try out this command in your terminal and if it doesn't post an error it'll execute the shortcut. Some people are reffering to files like XF86keysym.h and keysymdef.h (excluding XK_ from the beginning) to be a list of all shortcuts but there isn't listed everything... maybe someone will find where exactly can all be found.

`run` just runs the command with C system() function, so it could be everything, app, script (that user can run), whatever ... so if you wanna go extreme you can just use the power of shell and execute the script that way

and with the new version there's a new command `chmap` which just loads another mapping from that naga folder(if you wanna switch profiles).... so you basically put a filename there and that's it.

And in that case you could use for example BackSpace and Shift+BackSpace(or alt and arrow keys) or the special key but I'm not sure which one is that and this should work fine.

**Comment by apocatarsis** [comment]
1) Well, if you ask me I would just make different scripts (or even an entire new branch) for every new distribution we can get to work to improve readability. Maybe the installer could then look for the current distro and then run a script made for that distro.

2) Yes, testlab is an improved version of the program made by Destroyer, Sadly I cannot test it on my pc at the moment, that is why it is not in the master. But I will try to somehow store the current master (maybe as a release?) and make testlab the master.

3)I think that when I first wrote the program I saw a list of the available keys in the xdotools documentation, but I cannot find it at the moment. However, as Destroyer mentioned, you can see them at the header http://cgit.freedesktop.org/xorg/proto/x11proto/plain/keysymdef.h.

You can also use this information I found googling:
Use 'xev -event keyboard', unless you want to enter keys that you cannot actually type using your keyboard. In the latter case, use
grep "XK_" /usr/include/X11/keysymdef.h|sed 's/ XK_/ /g' (for most normal keysyms)
or 
grep "XK_" /usr/include/X11/XF86keysym.h|sed 's/XK_//g' (for 'multimedia keyboard' keysyms)

P.S. The chmap option is awesome!!

**Comment by noobxgockel** [comment]
To 2)
Works like a charm here, havent tested the chmap feature tho.
Here is the patch for my Naga Molten: (was too lazy to fork and stuffs)
http://paste.linuxmint.com/view/lv7g

As an update to 3)
the keysymdef doesnt contain any "internet" or media related buttons, thats were the back and forward is in. So that doesnt work, but i found out through using 'xev' that those two buttons are actually button 8 and 9. xdotool can emulate them with ```click``` instead of ```key```. For now i can write a script and use the "run" functionality, but it would be awesome if this tool can do this natively C:

**Comment by Destroyer** [comment]
1) That would be great, but I am not really familiar with packaging and this kind of stuff so that would be up to you. One thing that would be possible to do right now is to detect devices during install and correct nagastart script so that users wouldn't have to set it themselves. (if the device would be listed). 

2) My friend has been testing it for 5days and it looks stable. Only thing I am a little concerned is CPU usage, during mouse movement it's just an extra strain to the battery if the user is on a laptop e.g. I am not sure if there's even more efficient way to do it but for now I can't think of any. But there's the only problem I could think of. 
CPU usage is about 2% when high mouse movement which is almost nothing but still something if you need every extra minute and you use mouse a lot. But that is a minor thing I think.

3) Let us know if you find it because I couldn't :) 

chmap - thanks, that was the first thing I had to programm for my friend :) .  I don't have much time right now but I wanted to create one more option - `workspace=+` and `workspace=-` which would switch to the next workspace and to the previous one. But I am not sure which that syntax of xdotool if this can be done with 1 command or not.

**Comment by Destroyer** [comment]
Alright `workspace_r`, `workspace`, `click` added. More info in the readme.
Try it and let me know if it works for you ;)

**Comment by apocatarsis** [comment]
I merged your version with the master, everything should work fine, let me know. I think is a good idea to continue working at testlab and merge eventually when tested.

Thank you both for your ideas and effort!! Thanks to you the Mapper is now much much better!

**Comment by noobxgockel** [comment]
@apocatarsis i must thank you for providing such piece of software :D

@Destroyer Totally forgot to do feedback. Tested the workspace_r and click, both work flawlessly C:

**Comment by apocatarsis** [comment]
Closing then!
